on:
  pull_request:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.yml'
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          install-go: false
      - run: g++ -std=c++11 -Wno-noexcept-type -g -Wall -Wextra -Werror=return-type --verbose statshouse_test.cpp
  statshouse-client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: go run github.com/vkcom/statshouse/cmd/statshouse-client-test@master
